language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE users;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: I2wMkxeh25sounzK4ripRD3nooFdMhERl8rGA7gPOgxLg4JWU0M7gS5j5nTRelpPq6PG6lqr5lIvwAjo5zpRmeNKLvPAQx0aW8RO0ftNs9+gaCToIiB7EctLUXMy84lne4FTh0uyQ6C7H/rCb2I4AeHKwj08AfxGB8smQHA9DZgIXJV19dBKtULdmGvWgmEAaHiWCBb0IH26WvsPI+s1vBe+AYcNYY6Pvqs1McUTS1hpIrt9KeqtpX5o3D8ca7YxXahZbY8SrrgAY23ICOJ5RDmUemdkQL7/mj/V5kUGSLFEbvC5od3/F2+QYNe3sJq16/guWHilxV/RKFhoYL3lddHoK6Cvu6yc1RkG28oV8Mnr9jA5FXuQqovgbADwDV86gRLJumt/PIsUnloe0hnucpIjyFWNhawf6FPAIZTDdHv5eGzAuOmlUyXj/9y9qgzMZD2+jCisS+PRx6FVv5RJFUYMDU+vWTNUvMaz4Tw4UsqmJmknjALoCO5S8+6bYorsJrOL7eYmyRnBabhjW4O732bNN8kjKzCYMN5gr6vCw6P4rWkgDZQHgUGKf3xZMup4MRiwDRmHiou5kIR/d8wMBtGkiVvQF0uz/4jBM9SKQIfOEdOqj4flAcY9eUgkNFWkVxUojAdDuGJHXdRSN8BXuq5N/YY5moaODDQiUbgjjsE=
  app: veterinformant
  skip_cleanup: true
scripts:
  start: node server.js
  test: NODE_ENV=test jest --exit
